Repository vebhvv/Problem-statements, pull requests merged in 2022-10, with the labels that each got.

#1 Solved two problems
  C Solutions/odd-even.c
  C Solutions/steps-and-km.c
  Python Solutions/odd-even.py
  index.html
Labels: enhancement, Hacktoberfest-accepted

#5 Compute (n+nn+nnn)
  .vscode/settings.json
  C Solutions/n+nn+nnn.c
  C Solutions/n+nn+nnn.exe
  index.html
Labels: enhancement, help wanted, good first issue, Hacktoberfest-accepted

#8 Update index.html
  Python Solutions/problem.py
  index.html
Labels: good first issue, Hacktoberfest-accepted

#9 Solved problem in cpp
  C++ Solutions/n+nn+nnn.cpp
  README.md
  index.html
Labels: enhancement, good first issue, Hacktoberfest-accepted

#10 Factors of Number
  C++ Solutions/Factors of Number
Labels: good first issue, Hacktoberfest-accepted

#11 solved steps and km problem
  C++ Solutions/steps-and-km.cpp
  index.html
Labels: enhancement, good first issue, Hacktoberfest-accepted
